### ISSUE TITLE
Python hashlib functions not found on Debian

### ISSUE THREAD

**Issue by deric** [collectd/collectd#1010]
When some Python plugin is configured collectd fails to find Python hash functions:
```
/etc/init.d/collectd restart
[....] Restarting statistics collection and monitoring daemon: collectdERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
. ok 
```
all dependent libraries are installed:

```
ldd /usr/lib/python2.7/lib-dynload/_hashlib.so
        linux-vdso.so.1 =>  (0x00007fffb65ff000)
        libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f851663e000)
        libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f8516246000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8516029000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8515c9e000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8515a88000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8515883000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f851566c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8516aaf000)
```

when testing hashlib from console everything seems to work:
```
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import hashlib
>>> hashlib.sha224("Nobody inspects the spammish repetition").hexdigest()
'a4337bc45a8fc544c03f52dc550cd6e1e87021bc896588bd79e901e2'
>>> hashlib.md5("Nobody inspects the spammish repetition").hexdigest()
'bb649c83dd1ea5c9d9dec9a18df0ffe9'
```

**Comment by mfournier** [comment]
Which version of collectd is this?

Can you please paste the python plugin post of your collectd configuration file? Thanks!

**Comment by deric** [comment]
Debian Wheezy, latest stable version, `collectd 5.1.0-3`. I have there 2 config files, first one is named `10-python.conf`:

```
<LoadPlugin python>
  Globals false
</LoadPlugin>
```
file `11-python-modules.conf`
```
<Plugin "python">
  ModulePath "/usr/lib/collectd/python"

  Import "zk-collectd"

  <Module "zk-collectd">
      Host "localhost"
    </Module>
</Plugin>
```
Not sure if it is relevant, but package `libssl1.0.0` is in version `1.0.1e-2+deb7u16`

**Comment by mfournier** [comment]
@deric, this is puzzling :) I wonder if there might be some sort of namespace conflict. Could you try comparing `print sys.path` between the python CLI and your zk-collectd module ?

Also what else is there in `/usr/lib/collectd/python` ? Could there be some file which accidentally has the same name as one of the libraries hashlib depends on ?

A change related to python's load path has been added a couple of months ago. If you have a test environment available for this, I'd be grateful if you were able to check if the problem still occurs with the latest nightly build. There are packages for wheezy, see https://github.com/collectd/collectd-ci (in short, add this to the sources.list: `deb http://sos.exo.io/collectd/deb/ wheezy collectd-5.4` and upgrade the collectd and collectd-core packages). Thanks !

**Comment by deric** [comment]
Thanks for your time! It seems that it's not an issue of collectd, but other Python modules. There are just two modules in the Python folder and the other one is [collectd-mesos](https://github.com/rayrod2030/collectd-mesos). I've tried removing it from collectd config which didn't help (but obviously it's loaded anyway).

I guess the problem is, that collectd-mesos is not encapsulated in a class. It's just a bunch of methods and some of them might collide with other modules. Is it possible? The error message is not very helpful, however removing `mesos-slave.py` and `mesos-master-py` eliminates the error.

Should I try latest version of collectd or it's easier to refactor the mesos module?

**Comment by deric** [comment]
The problem was caused by the `Globals` variable, setting
```
<LoadPlugin python>
  Globals true
</LoadPlugin>
```
fix the issue. Next time I should read the documentation first :(.
