### ISSUE TITLE
collectd -T leaks a few bytes

### ISSUE THREAD

**Issue by rubenk** [collectd/collectd#1112]
Not a big issue but we might want to fix those nonetheless so they don't obscure more important leaks:

```
ruben@wodan: collectd (master %=)$ /opt/sbin/collectd -T

=================================================================
==18858==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 10 byte(s) in 1 object(s) allocated from:
    #0 0x4af58e in strdup (/opt/sbin/collectd+0x4af58e)
    #1 0x547685 in plugin_register_read /home/ruben/src/collectd/src/daemon/plugin.c:1241:16
    #2 0x7f6f472d8aad in module_register /home/ruben/src/collectd/src/interface.c:387:2
    #3 0x54513a in plugin_load_file /home/ruben/src/collectd/src/daemon/plugin.c:475:2
    #4 0x543f90 in plugin_load /home/ruben/src/collectd/src/daemon/plugin.c:1086:12
    #5 0x503168 in dispatch_loadplugin /home/ruben/src/collectd/src/daemon/configfile.c:316:12
    #6 0x4f75f5 in dispatch_value /home/ruben/src/collectd/src/daemon/configfile.c:367:23
    #7 0x4f5150 in cf_read /home/ruben/src/collectd/src/daemon/configfile.c:1129:4
    #8 0x4e847a in main /home/ruben/src/collectd/src/daemon/collectd.c:560:6
    #9 0x7f6f49f7f99f in __libc_start_main (/lib64/libc.so.6+0x2099f)

Direct leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x4af58e in strdup (/opt/sbin/collectd+0x4af58e)
    #1 0x547685 in plugin_register_read /home/ruben/src/collectd/src/daemon/plugin.c:1241:16
    #2 0x7f6f46ec9906 in module_register /home/ruben/src/collectd/src/memory.c:532:2
    #3 0x54513a in plugin_load_file /home/ruben/src/collectd/src/daemon/plugin.c:475:2
    #4 0x543f90 in plugin_load /home/ruben/src/collectd/src/daemon/plugin.c:1086:12
    #5 0x503168 in dispatch_loadplugin /home/ruben/src/collectd/src/daemon/configfile.c:316:12
    #6 0x4f75f5 in dispatch_value /home/ruben/src/collectd/src/daemon/configfile.c:367:23
    #7 0x4f5150 in cf_read /home/ruben/src/collectd/src/daemon/configfile.c:1129:4
    #8 0x4e847a in main /home/ruben/src/collectd/src/daemon/collectd.c:560:6
    #9 0x7f6f49f7f99f in __libc_start_main (/lib64/libc.so.6+0x2099f)

Direct leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x4af58e in strdup (/opt/sbin/collectd+0x4af58e)
    #1 0x547685 in plugin_register_read /home/ruben/src/collectd/src/daemon/plugin.c:1241:16
    #2 0x7f6f470d0d7d in module_register /home/ruben/src/collectd/src/load.c:218:2
    #3 0x54513a in plugin_load_file /home/ruben/src/collectd/src/daemon/plugin.c:475:2
    #4 0x543f90 in plugin_load /home/ruben/src/collectd/src/daemon/plugin.c:1086:12
    #5 0x503168 in dispatch_loadplugin /home/ruben/src/collectd/src/daemon/configfile.c:316:12
    #6 0x4f75f5 in dispatch_value /home/ruben/src/collectd/src/daemon/configfile.c:367:23
    #7 0x4f5150 in cf_read /home/ruben/src/collectd/src/daemon/configfile.c:1129:4
    #8 0x4e847a in main /home/ruben/src/collectd/src/daemon/collectd.c:560:6
    #9 0x7f6f49f7f99f in __libc_start_main (/lib64/libc.so.6+0x2099f)

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x4af58e in strdup (/opt/sbin/collectd+0x4af58e)
    #1 0x547685 in plugin_register_read /home/ruben/src/collectd/src/daemon/plugin.c:1241:16
    #2 0x7f6f474e8df3 in module_register /home/ruben/src/collectd/src/cpu.c:840:2
    #3 0x54513a in plugin_load_file /home/ruben/src/collectd/src/daemon/plugin.c:475:2
    #4 0x543f90 in plugin_load /home/ruben/src/collectd/src/daemon/plugin.c:1086:12
    #5 0x503168 in dispatch_loadplugin /home/ruben/src/collectd/src/daemon/configfile.c:316:12
    #6 0x4f75f5 in dispatch_value /home/ruben/src/collectd/src/daemon/configfile.c:367:23
    #7 0x4f5150 in cf_read /home/ruben/src/collectd/src/daemon/configfile.c:1129:4
    #8 0x4e847a in main /home/ruben/src/collectd/src/daemon/collectd.c:560:6
    #9 0x7f6f49f7f99f in __libc_start_main (/lib64/libc.so.6+0x2099f)

SUMMARY: AddressSanitizer: 26 byte(s) leaked in 4 allocation(s).
```

collectd configured with:
./configure CFLAGS="-fsanitize=address,undefined -g"

**Comment by rubenk** [comment]
This is fixed by 51f45d6b217b
