### ISSUE TITLE
ipmi in combination with java plugins crashes

### ISSUE THREAD

**Issue by fcorneli** [collectd/collectd#114]
When using the ipmi plugin in combination with the java plugin, collectd crashes.

```
[2012-08-08 13:57:42] java plugin: The JVM has been created.
[2012-08-08 13:57:42] java plugin: cjni_thread_attach: cjni_env->reference_counter = 1
[2012-08-08 13:57:42] java plugin: Loading class org/collectd/java/GenericJMX
[2012-08-08 13:57:42] java plugin: Registering new config callback: GenericJMX
[2012-08-08 13:57:42] java plugin: Registering new read callback: GenericJMX
[2012-08-08 13:57:42] java plugin: Registering new shutdown callback: GenericJMX
[2012-08-08 13:57:42] java plugin: cjni_thread_detach: cjni_env->reference_counter = 0
[2012-08-08 13:57:42] java plugin: Configuring GenericJMX
[2012-08-08 13:57:42] java plugin: cjni_thread_attach: cjni_env->reference_counter = 1
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f708559ee10, pid=27654, tid=140121236432640
#
# JRE version: 6.0_33-b03
# Java VM: Java HotSpot(TM) 64-Bit Server VM (20.8-b03 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x711e10][2012-08-08 13:57:42] GenericJMX plugin: config: ci = { key: Plugin; values: [GenericJMX]; children: [{ key: MBean; values: [memory_pool]; children: [{ key: ObjectName; values: [java.lang:type=MemoryPool,*]; children: []; }, { key: Instanceprefix; values: [memory_pool-]; children: []; }, { key: InstanceFrom; values: [name]; children: []; }, { key: Value; values: []; children: [{ key: Type; values: [memory]; children: []; }, { key: Table; values: [true]; children: []; }, { key: Attribute; values: [Usage]; children: []; }]; }]; }, { key: Connection; values: []; children: [{ key: Host; values: [e-contract.be]; children: []; }, { key: ServiceURL; values: [service:jmx:rmi:///jndi/rmi://localhost:1090/jmxrmi]; children: []; }, { key: Collect; values: [memory_pool]; children: []; }]; }]; };
  SR_handler(int, siginfo*, ucontext*)+0x30
#
# An error report file with more information is saved as:
# /opt/collectd/var/lib/collectd/hs_err_pid27654.log
[2012-08-08 13:57:42] GenericJMXConfMBean: child.getKey () = ObjectName
[2012-08-08 13:57:42] GenericJMXConfMBean: child.getKey () = Instanceprefix
[2012-08-08 13:57:42] GenericJMXConfMBean: child.getKey () = InstanceFrom
[2012-08-08 13:57:42] GenericJMXConfMBean: child.getKey () = Value
[2012-08-08 13:57:42] GenericJMX.putMBean: Adding memory_pool
[2012-08-08 13:57:42] GenericJMXConfConnection: e-contract.be: Add memory_pool
[2012-08-08 13:57:42] java plugin: cjni_thread_detach: cjni_env->reference_counter = 0
[2012-08-08 13:57:42] java plugin: jvm_argc = 2;
[2012-08-08 13:57:42] java plugin: java_classes_list_len = 1;
#
# If you would like to submit a bug report, please visit:
#   http://java.sun.com/webapps/bugreport/crash.jsp
[2012-08-08 13:57:42] java plugin: cjni_thread_attach: cjni_env->reference_counter = 1
#
[2012-08-08 13:57:42] java plugin: cjni_thread_detach: cjni_env->reference_counter = 0
Aborted
```

**Comment by vincentbernat** [comment]
I am also hit by this problem and 513a5ca doesn't solve it. It still happens with the master branch. I'll try to debug that.

**Comment by vincentbernat** [comment]
My current understanding is that OpenIPMI is using a signal to interrupt "wake" its event loop. It does that when timers are changed to be able to recompute the timeout correctly. This is a bit crazy design. However, it is also sending its signal to the exact same thread it is currently running (it is not currently blocked on select()).

I have the current bt:

```
Thread 12 (Thread 0x7fffefcb9700 (LWP 8942)):
#0  0x00007ffff5b8c89e in SR_handler(int, siginfo*, ucontext*) ()
   from /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#1  <signal handler called>
#2  0x00007ffff79c1f8c in pthread_kill () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007ffff6bd46c5 in wake_sel_thread (sel=0x7fffe8000b00) at selector.c:205
#4  0x00007ffff6bd5d4f in sel_start_timer (timer=0x7fffe8011000, timeout=0x7fffefcb89e0)
    at selector.c:478
#5  0x00007ffff6bd447a in start_timer (cb_data=<optimized out>, timed_out=<optimized out>,
    timeout=<optimized out>, id=0x7fffe8010f70, handler=<optimized out>)
    at posix_thread_os_hnd.c:211
#6  start_timer (handler=<optimized out>, id=0x7fffe8010f70, timeout=<optimized out>,
    timed_out=<optimized out>, cb_data=<optimized out>) at posix_thread_os_hnd.c:188
#7  0x00007ffff69768cc in finish_connection (ipmi=0x7fffe800cc90, smi=0x7fffe800cec0)
    at ipmi_smi.c:1268
#8  0x00007ffff6976a98 in handle_dev_id (ipmi=0x7fffe800cc90, msgi=<optimized out>)
    at ipmi_smi.c:1346
#9  0x00007ffff690fdb9 in ipmi_handle_rsp_item_copymsg (ipmi=0x7fffe800cc90,
    rspi=0x7fffe80111a0, msg=<optimized out>, rsp_handler=0x7ffff69769f0 <handle_dev_id>)
    at ipmi.c:1761
#10 0x00007ffff697630c in handle_response (recv=0x7fffefcb8aa0, ipmi=0x7fffe800cc90)
    at ipmi_smi.c:701
#11 gen_recv_msg (recv=0x7fffefcb8aa0, ipmi=0x7fffe800cc90) at ipmi_smi.c:874
#12 ipmi_dev_data_handler (cb_data=0x7fffe800cc90, fd=<optimized out>, id=<optimized out>)
    at ipmi_smi.c:922
#13 ipmi_dev_data_handler (fd=<optimized out>, cb_data=0x7fffe800cc90, id=<optimized out>)
    at ipmi_smi.c:892
#14 0x00007ffff6bd576d in process_fds (sel=0x7fffe8000b00, timeout=<optimized out>,
    send_sig=<optimized out>, thread_id=<optimized out>, cb_data=<optimized out>)
    at selector.c:636
#15 0x00007ffff6bd60a6 in sel_select (sel=0x7fffe8000b00,
    send_sig=0x7ffff6bd3990 <posix_thread_send_sig>, thread_id=140737216482920,
    cb_data=0x7fffe8000a40, timeout=0x7fffefcb8eb0) at selector.c:739
#16 0x00007ffff6bd4067 in perform_one_op (os_hnd=0x7fffe80008e0, timeout=0x7fffefcb8eb0)
    at posix_thread_os_hnd.c:639
#17 0x00007ffff6ddb560 in thread_main (user_data=<optimized out>) at ipmi.c:613
#18 0x00007ffff79bce9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#19 0x00007ffff72d62ed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#20 0x0000000000000000 in ?? ()
```

No other thread is currently running in `selector.c` (where the event loop is). It would be far better if OpenIPMI was using a file descriptor to wakeup its event loop when needed instead of a signal. All the more it should be a library. I have opened a bug against OpenIPMI for that:
 https://sourceforge.net/p/openipmi/bugs/72/

The second problem is that the Java plugin registered a signal

The problem is that the java plugin registered an handler for the very same signal for suspending/resuming its own thread. However, it is possible to change the signal to something else using `_JAVA_SR_SIGNUM=10` (this will cause other [bugs](https://bugs.openjdk.java.net/browse/JDK-4355769)).

OpenIPMI shouldn't use signals. A workaround is to export `_JAVA_SR_SIGNUM=25` (which is greater that SIGBUS and SIGSEGV on all architectures I think).
