### ISSUE TITLE
log_logstash plugin causing constant re-initialization

### ISSUE THREAD

**Issue by BCWilsonDotCom** [collectd/collectd#1257]
After enabling the log_logstash plugin, collectd.log is filled with the following message:

```
[2015-09-03 18:38:05] Initialization complete, entering read-loop.
[2015-09-03 18:39:10] Initialization complete, entering read-loop.
[2015-09-03 18:40:15] Initialization complete, entering read-loop.
[2015-09-03 18:41:20] Initialization complete, entering read-loop.
[2015-09-03 18:42:25] Initialization complete, entering read-loop.
[2015-09-03 18:43:30] Initialization complete, entering read-loop.
```

While the plugin is enabled, no threshold notifications are sent for plugin's values that cross the configured thresholds. Once the plugin is disabled, the "Initialization complete" message is only seen in collectd.log once, after the service starts. After that log messages are seen as expected, including threshold notifications.

The log_logstash.conf is as follows:
```
LoadPlugin "log_logstash"

<Plugin "log_logstash">

  LogLevel "notice"
  File  "/var/log/collectd_logstash.log"

</Plugin>
```

**Comment by mfournier** [comment]
This message is typically seen just once at startup. Could it be that collectd is crashing and is getting restarted by collectdmon or another process supervisor ? Can you try starting collectd in the foreground (`-f`) ?

**Comment by BCWilsonDotCom** [comment]
That appears to be exactly what is happening. I ran collectd in the foreground `collectd -f` and after about a minute it segfaulted. I do run collectdmon with collectd when started as a service, so that would be what's restarting it.

```
[Fri Sep 04 09:10:53] [root@srv-129-27:/var/log]#collectd -f
Segmentation fault
[Fri Sep 04 09:12:02] [root@srv-129-27:/var/log]#
```

**Comment by BCWilsonDotCom** [comment]
Here's some details:

```
(1:529)# seg_wrapper.sh collectd -f
/home/bwilson/bin/seg_wrapper.sh: line 3: 17699 Segmentation fault      (core dumped) "$@"
Reading symbols from /usr/sbin/collectd...Reading symbols from /usr/lib/debug/usr/sbin/collectd...done.
done.
[New LWP 17700]
[New LWP 17702]
[New LWP 17707]
[New LWP 17704]
[New LWP 17703]
[New LWP 17708]
[New LWP 17701]
[New LWP 17705]
[New LWP 17699]
[New LWP 17709]
[New LWP 17706]

warning: Can't read pathname for load map: Input/output error.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `collectd -f'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fb6206dea99 in yajl_gen_alloc2 () from /usr/lib/x86_64-linux-gnu/libyajl.so.1
#0  0x00007fb6206dea99 in yajl_gen_alloc2 () from /usr/lib/x86_64-linux-gnu/libyajl.so.1
No symbol table info available.
#1  0x00007fb6208e4257 in log_logstash_notification (n=0x7fb61cdd7940, user_data=<optimized out>) at log_logstash.c:258
        g = <optimized out>
        conf = {beautify = 0, indentString = 0x1 <Address 0x1 out of bounds>}
#2  0x000000000040b166 in plugin_dispatch_notification (notif=0x7fb61cdd7940) at plugin.c:2323
        cf = <optimized out>
        callback = <optimized out>
        status = <optimized out>
        le = 0xe281f0
#3  0x00007fb61cfe187d in ut_report_state (ds=0xe1c4d0, vl=<optimized out>, th=<optimized out>, values=0x7fb5f4004840, ds_index=0, state=1) at threshold.c:598
        state_old = 0
        n = {severity = 2, time = 1547677915364040024,
          message = "Host srv-110-01, plugin swap type swap (instance free): Data source \"value\" is currently 16967780.000000. That is below the warning threshold of 1000000000.000000.", '\000' <repeats 92 times>, host = "srv-110-01", '\000' <repeats 53 times>, plugin = "swap", '\000' <repeats 59 times>, plugin_instance = '\000' <repeats 63 times>,
          type = "swap", '\000' <repeats 59 times>, type_instance = "free", '\000' <repeats 59 times>, meta = 0x7fb5f4004d30}
        buf = 0x7fb61cdd7986 ": Data source \"value\" is currently 16967780.000000. That is below the warning threshold of 1000000000.000000."
        bufsize = 202
        status = <optimized out>
#4  0x00007fb61cfe1f01 in ut_check_threshold (ds=0xe1c4d0, vl=0x7fb600003280, ud=<optimized out>) at threshold.c:828
        th = 0x0
        values = 0x7fb5f4004840
        status = <optimized out>
        worst_state = 1
        worst_th = 0xeff3f0
        worst_ds_index = 0
#5  0x000000000040c50d in plugin_write (plugin=<optimized out>, ds=0xe1c4d0, vl=0x7fb600003280) at plugin.c:1767
        cf = <optimized out>
        callback = <optimized out>
        success = <optimized out>
        failure = <optimized out>
        le = 0xeff8f0
        status = <optimized out>
#6  0x0000000000408aed in fc_bit_write_invoke (ds=0xe1c4d0, vl=0x7fb600003280, meta=<optimized out>, user_data=<optimized out>) at filter_chain.c:726
        write_complaint = {last = 0, interval = 0, complained_once = false}
        plugin_list = <optimized out>
        status = <optimized out>
#7  0x0000000000409415 in fc_process_chain (ds=0xe1c4d0, vl=0x7fb600003280, chain=0xec1f80) at filter_chain.c:1017
        rule = 0x0
        target = 0xe88f40
        status = <optimized out>
---Type <return> to continue, or q <return> to quit---
        __PRETTY_FUNCTION__ = "fc_process_chain"
#8  0x000000000040b486 in plugin_dispatch_values_internal (vl=0x7fb600003280) at plugin.c:2096
        status = <optimized out>
        no_write_complaint = {last = 0, interval = 0, complained_once = false}
        saved_values = <optimized out>
        saved_values_len = <optimized out>
        ds = 0xe1c4d0
        free_meta_data = 1
        __PRETTY_FUNCTION__ = "plugin_dispatch_values_internal"
#9  0x000000000040dd19 in plugin_write_thread (args=<optimized out>) at plugin.c:838
        vl = 0x7fb600003280
#10 0x00007fb6212b9e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#11 0x00007fb620ddd38d in clone () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#12 0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by mfournier** [comment]
a9b65b73fc fixes this issue. It will be part of 5.5.1.
