### ISSUE TITLE
curl_json plugin in 5.5.0 causes general protection kernel error with long json key

### ISSUE THREAD

**Issue by eLco** [collectd/collectd#1261]
Collectd built from 5.5.0 source - crashes with error in syslog:
```
collectd[19696]: python: Plugin loaded but not configured.
collectd[19696]: Initialization complete, entering read-loop.
kernel: [1704255.248100] do_general_protection: 2 callbacks suppressed
kernel: [1704255.248105] collectd[19711] general protection ip:7fe8532ed194 sp:7fe849137260 error:0 in libpthread-2.13.so[7fe8532e4000+17000]
collectdmon[19688]: Warning: collectd was terminated by signal 11 (core dumped)
collectdmon[19688]: Warning: restarting collectd
```
Configuration:
```
LoadPlugin curl_json
<Plugin curl_json>
 <URL "http://127.0.0.1:5080/api/metrics">
   Instance "Kafka"
    <Key "kafka.server.BrokerTopicMetrics/BytesInPerSec/count">
      Type "counter"
    </Key>
    <Key "kafka.server.BrokerTopicMetrics/MessagesInPerSec/count">
      Type "counter"
    </Key>
    <Key "kafka.server.BrokerTopicMetrics/BytesOutPerSec/count">
      Type "counter"
    </Key>
    <Key "kafka.network.RequestMetrics.request.Produce/RequestsPerSec/count">
      Type "counter"
    </Key>
    <Key "kafka.network.RequestMetrics.request.FetchConsumer/RequestsPerSec/count">
      Type "counter"
    </Key>
</URL>
</Plugin>
```
Crashlog:

```
gdb /usr/local/collectd/sbin/collectd /usr/local/collectd/var/lib/collectd/core.17642
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/collectd/sbin/collectd...done.
[New LWP 17656]
[New LWP 17650]
[New LWP 17659]
[New LWP 17651]
[New LWP 17652]
[New LWP 17658]
[New LWP 17653]
[New LWP 17657]
[New LWP 17660]
[New LWP 17654]
[New LWP 17642]
[New LWP 17655]

warning: Can't read pathname for load map: Input/output error.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/collectd/sbin/collectd -C /usr/local/collectd/etc/collectd.conf -f'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f2673e22194 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
(gdb) backtrace full
#0  0x00007f2673e22194 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#1  0x000000000040c769 in meta_data_clone (orig=0x6f632d0000000000) at meta_data.c:246
        copy = 0x7f2660001eb0
#2  0x000000000040e481 in plugin_value_list_clone (vl_orig=0x7f266a468970) at plugin.c:720
        vl = 0x7f266000c5d0
#3  0x000000000040e5d4 in plugin_write_enqueue (vl=0x7f266a468970) at plugin.c:764
        q = 0x7f266000c5b0
#4  0x0000000000410ecc in plugin_dispatch_values (vl=0x7f266a468970) at plugin.c:2203
        status = 0
        statistics_lock = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}
#5  0x00007f26706f99e3 in cj_submit (db=0x25387b0, key=0x253b940, value=0x7f266a468b30) at curl_json.c:872
        vl = {values = 0x7f266a468b30, values_len = 1, time = 0, interval = 5368709120, host = "afm-kafka001iad.io.askjeeves.info", '\000' <repeats 30 times>, plugin = "curl_json", '\000' <repeats 54 times>,
          plugin_instance = "Kafka", '\000' <repeats 58 times>, type = "counter", '\000' <repeats 56 times>, type_instance = "kafka.network.RequestMetrics.request.FetchConsumer-RequestQueue", meta = 0x6f632d0000000000}
        host = 0x639e00 "afm-kafka001iad.io.askjeeves.info"
#6  0x00007f26706f7ddb in cj_cb_number (ctx=0x25387b0,
    number=0x255b892 "473737,\"min\":0.0,\"max\":20.0,\"mean\":0.04258692059096081,\"std_dev\":0.20580699962389928,\"median\":0.0,\"p75\":0.0,\"p95\":0.0,\"p98\":1.0,\"p99\":1.0,\"p999\":1.0},\"RequestsPerSec\":{\"type\":\"meter\",\"event_type\":\"req"..., number_len=6) at curl_json.c:257
        buffer = 0x7f266a468b00 "473737"
        db = 0x25387b0
        key = 0x253b940
        vt = {counter = 473737, gauge = 2.3405717686389461e-318, derive = 473737, absolute = 473737}
        type = 0
        status = 0
#7  0x00007f26704ef629 in ?? () from /usr/lib/x86_64-linux-gnu/libyajl.so.2
No symbol table info available.
#8  0x00007f26706f790c in cj_curl_callback (buf=0x255b720, size=1, nmemb=3999, user_data=0x25387b0) at curl_json.c:127
        db = 0x25387b0
---Type <return> to continue, or q <return> to quit---
        len = 3999
        status = 32550
#9  0x00007f267029a810 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
No symbol table info available.
#10 0x00007f26702b803c in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
No symbol table info available.
#11 0x00007f26702b251a in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
No symbol table info available.
#12 0x00007f26702b3bf7 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
No symbol table info available.
#13 0x00007f26706f9c05 in cj_curl_perform (db=0x25387b0) at curl_json.c:920
        status = 32550
        rc = 139802968493632
        url = 0x25277e0 "http://127.0.0.1:5080/api/metrics"
#14 0x00007f26706f9d6c in cj_perform (db=0x25387b0) at curl_json.c:961
        status = 0
        yprev = 0x0
#15 0x00007f26706f9f46 in cj_read (ud=0x2563c48) at curl_json.c:1012
        db = 0x25387b0
#16 0x000000000040df6d in plugin_read_thread (args=0x0) at plugin.c:575
        callback = 0x7f26706f9e81 <cj_read>
        rf = 0x2563c40
        old_ctx = {interval = 0}
        status = 0
        rf_type = 1
        now = 1548004831851731794
        rc = 0
        __PRETTY_FUNCTION__ = "plugin_read_thread"
---Type <return> to continue, or q <return> to quit---
#17 0x00007f2673e1fb50 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#18 0x00007f267355295d in clone () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#19 0x0000000000000000 in ?? ()
No symbol table info available.
(gdb) quit
```

Key with such length is ok:
```
    <Key "kafka.network.RequestMetrics.request.Produce/RequestsPerSec/count">
      Type "counter"
    </Key>
```
JSON for this key:
```
  "kafka.network.RequestMetrics.request.Produce" : {
    "LocalTimeMs" : {
      "type" : "histogram",
      "count" : 34,
      "min" : 0.0,
      "max" : 18.0,
      "mean" : 2.235294117647059,
      "std_dev" : 4.559763573944091,
      "median" : 1.0,
      "p75" : 2.0,
      "p95" : 18.0,
      "p98" : 18.0,
      "p99" : 18.0,
      "p999" : 18.0
    },
    "RemoteTimeMs" : {
      "type" : "histogram",
      "count" : 34,
      "min" : 0.0,
      "max" : 0.0,
      "mean" : 0.0,
      "std_dev" : 0.0,
      "median" : 0.0,
      "p75" : 0.0,
      "p95" : 0.0,
      "p98" : 0.0,
      "p99" : 0.0,
      "p999" : 0.0
    },
    "RequestQueueTimeMs" : {
      "type" : "histogram",
      "count" : 34,
      "min" : 0.0,
      "max" : 6.0,
      "mean" : 0.4117647058823529,
      "std_dev" : 1.1313078261483283,
      "median" : 0.0,
      "p75" : 0.0,
      "p95" : 3.0,
      "p98" : 6.0,
      "p99" : 6.0,
      "p999" : 6.0
    },
    "RequestsPerSec" : {
      "type" : "meter",
      "event_type" : "requests",
      "unit" : "seconds",
      "count" : 34,
      "mean" : 0.10455691079562526,
      "m1" : 0.10476092525055351,
      "m5" : 0.08009298746831876,
      "m15" : 0.03363552603962718
    },
    "ResponseQueueTimeMs" : {
      "type" : "histogram",
      "count" : 34,
      "min" : 0.0,
      "max" : 1.0,
      "mean" : 0.14705882352941177,
      "std_dev" : 0.359490627953571,
      "median" : 0.0,
      "p75" : 0.0,
      "p95" : 1.0,
      "p98" : 1.0,
      "p99" : 1.0,
      "p999" : 1.0
    },
    "ResponseSendTimeMs" : {
      "type" : "histogram",
      "count" : 34,
      "min" : 0.0,
      "max" : 1.0,
      "mean" : 0.14705882352941177,
      "std_dev" : 0.35949062795357095,
      "median" : 0.0,
      "p75" : 0.0,
      "p95" : 1.0,
      "p98" : 1.0,
      "p99" : 1.0,
      "p999" : 1.0
    },
    "TotalTimeMs" : {
      "type" : "histogram",
      "count" : 34,
      "min" : 0.0,
      "max" : 20.0,
      "mean" : 2.9411764705882355,
      "std_dev" : 5.233581405839677,
      "median" : 1.0,
      "p75" : 2.0,
      "p95" : 19.25,
      "p98" : 20.0,
      "p99" : 20.0,
      "p999" : 20.0
    }
  },

```

And key with such length, causes crash:
```
    <Key "kafka.network.RequestMetrics.request.FetchConsumer/RequestsPerSec/count">
      Type "counter"
    </Key>
```
JSON for this key:
```
  "kafka.network.RequestMetrics.request.FetchConsumer" : {
    "LocalTimeMs" : {
      "type" : "histogram",
      "count" : 1298,
      "min" : 0.0,
      "max" : 1.0,
      "mean" : 0.05855161787365177,
      "std_dev" : 0.2348740653090943,
      "median" : 0.0,
      "p75" : 0.0,
      "p95" : 1.0,
      "p98" : 1.0,
      "p99" : 1.0,
      "p999" : 1.0
    },
    "RemoteTimeMs" : {
      "type" : "histogram",
      "count" : 1298,
      "min" : 0.0,
      "max" : 103.0,
      "mean" : 99.39060092449922,
      "std_dev" : 7.733662379129018,
      "median" : 100.0,
      "p75" : 100.0,
      "p95" : 101.0,
      "p98" : 101.0,
      "p99" : 101.0,
      "p999" : 101.0
    },
    "RequestQueueTimeMs" : {
      "type" : "histogram",
      "count" : 1298,
      "min" : 0.0,
      "max" : 1.0,
      "mean" : 0.07164869029275808,
      "std_dev" : 0.25800472732810437,
      "median" : 0.0,
      "p75" : 0.0,
      "p95" : 1.0,
      "p98" : 1.0,
      "p99" : 1.0,
      "p999" : 1.0
    },
    "RequestsPerSec" : {
      "type" : "meter",
      "event_type" : "requests",
      "unit" : "seconds",
      "count" : 1298,
      "mean" : 3.9935921559783245,
      "m1" : 8.733622600876634,
      "m5" : 3.495015939178446,
      "m15" : 1.3406357455153464
    },
    "ResponseQueueTimeMs" : {
      "type" : "histogram",
      "count" : 1298,
      "min" : 0.0,
      "max" : 1.0,
      "mean" : 0.04699537750385208,
      "std_dev" : 0.2117105171645386,
      "median" : 0.0,
      "p75" : 0.0,
      "p95" : 0.0,
      "p98" : 1.0,
      "p99" : 1.0,
      "p999" : 1.0
    },
    "ResponseSendTimeMs" : {
      "type" : "histogram",
      "count" : 1298,
      "min" : 0.0,
      "max" : 3.0,
      "mean" : 0.08859784283513097,
      "std_dev" : 0.3026626226107937,
      "median" : 0.0,
      "p75" : 0.0,
      "p95" : 1.0,
      "p98" : 1.0,
      "p99" : 1.0,
      "p999" : 2.0
    },
    "TotalTimeMs" : {
      "type" : "histogram",
      "count" : 1298,
      "min" : 0.0,
      "max" : 103.0,
      "mean" : 99.65639445300462,
      "std_dev" : 7.668676433828346,
      "median" : 100.0,
      "p75" : 101.0,
      "p95" : 101.0,
      "p98" : 101.0,
      "p99" : 102.0,
      "p999" : 102.971
    }
  },
```

**Comment by mfournier** [comment]
Not sure this is exactly the same problem, but it reminds me of #1156.
