### ISSUE TITLE
collectd terminated with SIGABRT

### ISSUE THREAD

**Issue by mdubbyap** [collectd/collectd#1505]
I'm experiencing an issue with collectd 5.5.0 crashing periodically.    The only difference between 5.5.0 and my build is DATA_MAX_NAME_LEN is 128 instead of 64.   

Os version is Ubuntu `14.04.3 LTS`.

Plugins loaded are:

LoadPlugin logfile
LoadPlugin cpu
LoadPlugin cpufreq
LoadPlugin interface
LoadPlugin load
LoadPlugin memory
LoadPlugin network
LoadPlugin protocols
LoadPlugin uptime
LoadPlugin aggregation
LoadPlugin match_regex
LoadPlugin java
LoadPlugin "org.collectd.java.GenericJMX"
LoadPlugin statsd
LoadPlugin write_http

Syslog is rather uninformative about it:

```
/var/log/syslog:Jan 11 07:02:42 ip-10-9-64-40 collectdmon[5677]: Warning: collectd was terminated by signal 6 (core dumped) 
/var/log/syslog:Jan 11 07:02:42 ip-10-9-64-40 collectdmon[5677]: Warning: restarting collectd
```

Stack trace from core below.  Thoughts?
```
[New LWP 8690] 
[New LWP 8692] 
[New LWP 8691] 
[New LWP 8694] 
[New LWP 8683] 
[New LWP 8682] 
[New LWP 8695] 
[New LWP 8697] 
[New LWP 8688] 
[New LWP 8689] 
[New LWP 8701] 
[New LWP 8698] 
[New LWP 8677] 
[New LWP 8696] 
[New LWP 8678] 
[New LWP 8672] 
[New LWP 8673] 
[New LWP 8687] 
[New LWP 8679] 
[New LWP 8675] 
[New LWP 8693] 
[New LWP 8676] 
[New LWP 8674] 
[New LWP 8685] 
[New LWP 8686] 
[New LWP 8684] 
[New LWP 8681] 
[New LWP 8680] 
[Thread debugging using libthread_db enabled] 
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1". 
Core was generated by `collectd -C /etc/collectd/collectd.conf -f'. 
Program terminated with signal SIGABRT, Aborted. 
#0 0x00007f216ca4fcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56 
#0 0x00007f216ca4fcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56 
#1 0x00007f216ca530d8 in __GI_abort () at abort.c:89 
#2 0x00007f216a20c579 in os::abort(bool) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a39328f in VMError::report_and_die() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f216a21529f in JVM_handle_linux_signal () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#5 <signal handler called> 
#6 0x00007f21693222df in ?? () from /usr/lib/collectd/statsd.so 
#7 0x00007f2169321feb in ?? () from /usr/lib/collectd/statsd.so 
#8 0x00007f216cff0182 in start_thread (arg=0x7f2156691700) at pthread_create.c:312 
#9 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 28 (Thread 0x7f215d270700 (LWP 8680)): 
#0 pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185 
#1 0x00007f216a212b1b in os::PlatformEvent::park() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a1d5017 in Monitor::IWait(Thread*, long) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a1d5c2f in Monitor::wait(bool, long, bool) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f2169f8828a in GCTaskManager::get_task(unsigned int) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#5 0x00007f2169f89bde in GCTaskThread::run() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#6 0x00007f216a20b742 in java_start(Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#7 0x00007f216cff0182 in start_thread (arg=0x7f215d270700) at pthread_create.c:312 
#8 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 27 (Thread 0x7f215d16f700 (LWP 8681)): 
#0 pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185 
#1 0x00007f216a212b1b in os::PlatformEvent::park() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a1d5017 in Monitor::IWait(Thread*, long) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a1d5c2f in Monitor::wait(bool, long, bool) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f2169f8828a in GCTaskManager::get_task(unsigned int) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#5 0x00007f2169f89bde in GCTaskThread::run() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#6 0x00007f216a20b742 in java_start(Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#7 0x00007f216cff0182 in start_thread (arg=0x7f215d16f700) at pthread_create.c:312 
#8 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 26 (Thread 0x7f2156c97700 (LWP 8684)): 
#0 pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185 
#1 0x00007f216a212b1b in os::PlatformEvent::park() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a1ffb55 in ObjectMonitor::wait(long, bool, Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a06a560 in JVM_MonitorWait () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f215edd1d98 in ?? () 
#5 0x00007f2156c968a0 in ?? () 
#6 0x0000000001a7a800 in ?? () 
#7 0x0000000001a77da0 in ?? () 
#8 0x00007f2156c96888 in ?? () 
#9 0x0000000616402720 in ?? () 
#10 0x00007f2156c968f8 in ?? () 
#11 0x00000006164bc080 in ?? () 
#12 0x0000000000000000 in ?? ()

Thread 25 (Thread 0x7f2156a95700 (LWP 8686)): 
#0 pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185 
#1 0x00007f216a212b1b in os::PlatformEvent::park() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a1d5017 in Monitor::IWait(Thread*, long) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a1d5ac6 in Monitor::wait(bool, long, bool) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f2169e84d0f in CompileQueue::get() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#5 0x00007f2169e8921c in CompileBroker::compiler_thread_loop() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#6 0x00007f216a345c70 in JavaThread::thread_main_inner() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#7 0x00007f216a345ee1 in JavaThread::run() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#8 0x00007f216a20b742 in java_start(Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#9 0x00007f216cff0182 in start_thread (arg=0x7f2156a95700) at pthread_create.c:312 
#10 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 24 (Thread 0x7f2156b96700 (LWP 8685)): 
#0 sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85 
#1 0x00007f216a20e071 in os::signal_wait() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a2069a1 in signal_thread_entry(JavaThread*, Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a345c70 in JavaThread::thread_main_inner() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f216a345ee1 in JavaThread::run() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#5 0x00007f216a20b742 in java_start(Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#6 0x00007f216cff0182 in start_thread (arg=0x7f2156b96700) at pthread_create.c:312 
#7 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 23 (Thread 0x7f216481f700 (LWP 8674)): 
#0 pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185 
#1 0x000000000040d49f in ?? () 
#2 0x00007f216cff0182 in start_thread (arg=0x7f216481f700) at pthread_create.c:312 
#3 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 22 (Thread 0x7f216381d700 (LWP 8676)): 
#0 pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185 
#1 0x000000000040d49f in ?? () 
#2 0x00007f216cff0182 in start_thread (arg=0x7f216381d700) at pthread_create.c:312 
#3 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 21 (Thread 0x7f2154e8e700 (LWP 8693)): 
#0 pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238 
#1 0x000000000040df1e in ?? () 
#2 0x00007f216cff0182 in start_thread (arg=0x7f2154e8e700) at pthread_create.c:312 
#3 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 20 (Thread 0x7f216401e700 (LWP 8675)): 
#0 pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185 
#1 0x000000000040d49f in ?? () 
#2 0x00007f216cff0182 in start_thread (arg=0x7f216401e700) at pthread_create.c:312 
#3 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 19 (Thread 0x7f215d371700 (LWP 8679)): 
#0 pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185 
#1 0x00007f216a212b1b in os::PlatformEvent::park() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a1d5017 in Monitor::IWait(Thread*, long) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a1d5c2f in Monitor::wait(bool, long, bool) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f2169f8828a in GCTaskManager::get_task(unsigned int) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#5 0x00007f2169f89bde in GCTaskThread::run() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#6 0x00007f216a20b742 in java_start(Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#7 0x00007f216cff0182 in start_thread (arg=0x7f215d371700) at pthread_create.c:312 
#8 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 18 (Thread 0x7f2156994700 (LWP 8687)): 
#0 pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185 
#1 0x00007f216a212b1b in os::PlatformEvent::park() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a1d5017 in Monitor::IWait(Thread*, long) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a1d5ac6 in Monitor::wait(bool, long, bool) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f2169e84d0f in CompileQueue::get() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#5 0x00007f2169e8921c in CompileBroker::compiler_thread_loop() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#6 0x00007f216a345c70 in JavaThread::thread_main_inner() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#7 0x00007f216a345ee1 in JavaThread::run() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#8 0x00007f216a20b742 in java_start(Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#9 0x00007f216cff0182 in start_thread (arg=0x7f2156994700) at pthread_create.c:312 
#10 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 17 (Thread 0x7f2165020700 (LWP 8673)): 
#0 pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185 
#1 0x000000000040d49f in ?? () 
#2 0x00007f216cff0182 in start_thread (arg=0x7f2165020700) at pthread_create.c:312 
#3 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 16 (Thread 0x7f216d419740 (LWP 8672)): 
#0 0x00007f216cff7b9d in nanosleep () at ../sysdeps/unix/syscall-template.S:81 
#1 0x00000000004065cf in main ()

Thread 15 (Thread 0x7f215d472700 (LWP 8678)): 
#0 pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185 
#1 0x00007f216a212b1b in os::PlatformEvent::park() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a1d5017 in Monitor::IWait(Thread*, long) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a1d5c2f in Monitor::wait(bool, long, bool) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f2169f8828a in GCTaskManager::get_task(unsigned int) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#5 0x00007f2169f89bde in GCTaskThread::run() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#6 0x00007f216a20b742 in java_start(Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#7 0x00007f216cff0182 in start_thread (arg=0x7f215d472700) at pthread_create.c:312 
#8 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 14 (Thread 0x7f214e43f700 (LWP 8696)): 
#0 pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238 
#1 0x00007f216a213730 in Parker::park(bool, long) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a36bec9 in Unsafe_Park () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f215edd1d98 in ?? () 
#4 0x00007f214e43e6f8 in ?? () 
#5 0x00000006168b9f08 in ?? () 
#6 0x0000000616a5b2e8 in ?? () 
#7 0x00000006168b8b80 in ?? () 
#8 0x0000000000000000 in ?? ()

Thread 13 (Thread 0x7f216301c700 (LWP 8677)): 
#0 pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185 
#1 0x000000000040d49f in ?? () 
#2 0x00007f216cff0182 in start_thread (arg=0x7f216301c700) at pthread_create.c:312 
#3 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 12 (Thread 0x7f214e23d700 (LWP 8698)): 
#0 pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238 
#1 0x00007f216a212d62 in os::PlatformEvent::park(long) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a1ffb3f in ObjectMonitor::wait(long, bool, Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a06a560 in JVM_MonitorWait () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f215edd1d98 in ?? () 
#5 0x000000061655e930 in ?? () 
#6 0x0000000000000000 in ?? ()

Thread 11 (Thread 0x7f214e13c700 (LWP 8701)): 
#0 pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238 
#1 0x00007f216a212d62 in os::PlatformEvent::park(long) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a21309d in os::sleep(Thread*, long, bool) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a074522 in JVM_Sleep () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f215edd1d98 in ?? () 
#5 0x00007f214e13b970 in ?? () 
#6 0x00007f215edc5350 in ?? () 
#7 0x00007f215edc58e1 in ?? () 
#8 0x00007f214e13b918 in ?? () 
#9 0x0000000000000000 in ?? ()

Thread 10 (Thread 0x7f2156792700 (LWP 8689)): 
#0 pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238 
#1 0x00007f216a212d62 in os::PlatformEvent::park(long) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a1d5174 in Monitor::IWait(Thread*, long) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a1d5c2f in Monitor::wait(bool, long, bool) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f216a340d13 in WatcherThread::sleep() const () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#5 0x00007f216a340dfe in WatcherThread::run() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#6 0x00007f216a20b742 in java_start(Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#7 0x00007f216cff0182 in start_thread (arg=0x7f2156792700) at pthread_create.c:312 
#8 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 9 (Thread 0x7f2156893700 (LWP 8688)): 
#0 pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185 
#1 0x00007f216a212b1b in os::PlatformEvent::park() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a1d5017 in Monitor::IWait(Thread*, long) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a1d5c2f in Monitor::wait(bool, long, bool) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f216a2a3b1e in ServiceThread::service_thread_entry(JavaThread*, Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#5 0x00007f216a345c70 in JavaThread::thread_main_inner() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#6 0x00007f216a345ee1 in JavaThread::run() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#7 0x00007f216a20b742 in java_start(Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#8 0x00007f216cff0182 in start_thread (arg=0x7f2156893700) at pthread_create.c:312 
#9 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 8 (Thread 0x7f214e33e700 (LWP 8697)): 
#0 pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238 
#1 0x00007f216a212d62 in os::PlatformEvent::park(long) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a1ffb3f in ObjectMonitor::wait(long, bool, Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a06a560 in JVM_MonitorWait () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f215edd1d98 in ?? () 
#5 0x00007f214e33d840 in ?? () 
#6 0x00007f2104088800 in ?? () 
#7 0x00007f210402fa20 in ?? () 
#8 0x00007f214e33d828 in ?? () 
#9 0x0000000000000000 in ?? ()

Thread 7 (Thread 0x7f214f7fe700 (LWP 8695)): 
#0 pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238 
#1 0x000000000040df1e in ?? () 
#2 0x00007f216cff0182 in start_thread (arg=0x7f214f7fe700) at pthread_create.c:312 
#3 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 6 (Thread 0x7f2156e99700 (LWP 8682)): 
#0 pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238 
#1 0x00007f216a212d62 in os::PlatformEvent::park(long) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a1d5174 in Monitor::IWait(Thread*, long) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a1d5c2f in Monitor::wait(bool, long, bool) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f216a3979b9 in VMThread::loop() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#5 0x00007f216a397c82 in VMThread::run() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#6 0x00007f216a20b742 in java_start(Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#7 0x00007f216cff0182 in start_thread (arg=0x7f2156e99700) at pthread_create.c:312 
#8 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 5 (Thread 0x7f2156d98700 (LWP 8683)): 
#0 pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185 
#1 0x00007f216a212b1b in os::PlatformEvent::park() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#2 0x00007f216a1ffb55 in ObjectMonitor::wait(long, bool, Thread*) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a06a560 in JVM_MonitorWait () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f215edd1d98 in ?? () 
#5 0x00000000000000c3 in ?? () 
#6 0x0000000000000000 in ?? ()

Thread 4 (Thread 0x7f214ffff700 (LWP 8694)): 
#0 pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238 
#1 0x000000000040df1e in ?? () 
#2 0x00007f216cff0182 in start_thread (arg=0x7f214ffff700) at pthread_create.c:312 
#3 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 3 (Thread 0x7f2155e90700 (LWP 8691)): 
#0 pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238 
#1 0x000000000040df1e in ?? () 
#2 0x00007f216cff0182 in start_thread (arg=0x7f2155e90700) at pthread_create.c:312 
#3 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7f215568f700 (LWP 8692)): 
#0 pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238 
#1 0x000000000040df1e in ?? () 
#2 0x00007f216cff0182 in start_thread (arg=0x7f215568f700) at pthread_create.c:312 
#3 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7f2156691700 (LWP 8690)): 
#0 0x00007f216ca4fcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56 
#1 0x00007f216ca530d8 in __GI_abort () at abort.c:89 
#2 0x00007f216a20c579 in os::abort(bool) () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#3 0x00007f216a39328f in VMError::report_and_die() () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#4 0x00007f216a21529f in JVM_handle_linux_signal () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so 
#5 <signal handler called> 
#6 0x00007f21693222df in ?? () from /usr/lib/collectd/statsd.so 
#7 0x00007f2169321feb in ?? () from /usr/lib/collectd/statsd.so 
#8 0x00007f216cff0182 in start_thread (arg=0x7f2156691700) at pthread_create.c:312 
#9 0x00007f216cb1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by mfournier** [comment]
Thanks for the detailed bugreport @mdubbyap !

There have been quite a few bugfixes to the collectd-5.5 branch since the 5.5.0 release. Would you mind giving the tip of the collectd-5.5 branch a try ? We have nightly builds for ubuntu available: https://github.com/collectd/collectd-ci/blob/master/README.md

**Comment by mdubbyap** [comment]
So using the latest 5.5 branch appears to have solved our issue.  Thanks!

matthew.
