### ISSUE TITLE
potential null dereference in snmp_agent plugin

### ISSUE THREAD

**Issue by rubenk** [collectd/collectd#2338]
```
  CC       src/snmp_agent_la-snmp_agent.lo
src/snmp_agent.c:423:8: warning: Dereference of null pointer
  if (!(*dd)->table->index_oid.oid_len) {
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

**Comment by rubenk** [comment]
(*dd)->table can be NULL here, but I'm not sure of the correct fix.

@vmytnykx would you mind taking a look?

**Comment by rpv-tomsk** [comment]
CC @rkorynkx

**Comment by rpv-tomsk** [comment]
That is not potential but real issue.

```
Core was generated by `/opt/collectd/sbin/collectd -C /opt/collectd-snmp_agent-test.conf -f'.
Program terminated with signal 11, Segmentation fault.
#0  snmp_agent_free_data (dd=0x8443b44) at src/snmp_agent.c:423
423       if (!(*dd)->table->index_oid.oid_len) {
(gdb) bt full
#0  snmp_agent_free_data (dd=0x8443b44) at src/snmp_agent.c:423
No locals.
#1  0xb74ccb58 in snmp_agent_free_config () at src/snmp_agent.c:1495
        de = <optimized out>
#2  0xb74ce6e0 in snmp_agent_config (ci=0x8421198) at src/snmp_agent.c:1561
        ret = <optimized out>
#3  0x08050136 in dispatch_block_plugin (ci=0x8421198) at src/daemon/configfile.c:395
        old_ctx = {interval = 0, flush_interval = 0, flush_timeout = 0}
        ret_val = <optimized out>
        cb = 0x8431998
        name = 0x84254f8 "snmp_agent"
#4  0x080505c8 in dispatch_block (ci=<optimized out>) at src/daemon/configfile.c:423
No locals.
#5  cf_read (filename=0xbfe6fe54 "/opt/collectd-snmp_agent-test.conf") at src/daemon/configfile.c:1020
        i = 10
        conf = 0x8421088
        ret = 0
#6  0x0804d545 in main (argc=4, argv=0xbfe6de54) at src/daemon/collectd.c:522
```

That binary was build from bea5daaed7b5cf9160207a95292947873fdcf927 

The configuration itself is very simple:

```
Hostname "test"
FQDNLookup false

PIDFile     "/var/run/collectd-xxx.pid"

LoadPlugin syslog
LoadPlugin logfile

<Plugin logfile>
LogLevel debug
#       LogLevel info
        File STDOUT
#       Timestamp true
#       PrintSeverity false
</Plugin>

<Plugin syslog>
       LogLevel info
</Plugin>

LoadPlugin network
<Plugin network>
    <Server "1.2.3.4" "25826">
    </Server>
    ReportStats false
</Plugin>

LoadPlugin snmp_agent

<Plugin snmp_agent>
    <Data "memAvailReal">
      Plugin "memory"
      Type "memory"
      TypeInstance "free"
      OIDs "1.3.6.1.4.1.2021.4.6.0"
    </Data>
    <Table "ifTable">
      IndexOID "IF-MIB::ifIndex"
      SizeOID "IF-MIB::ifNumber"
      <Data "ifDescr">
        Instance true
        Plugin "interface"
        OIDs "IF-MIB::ifDescr"
      </Data>
      <Data "ifOctets">
        Plugin "interface"
        Type "if_octets"
        TypeInstance ""
        OIDs "IF-MIB::ifInOctets" "IF-MIB::ifOutOctets"
      </Data>
    </Table>
</Plugin>
```

It fails when complains on bad configuration in

```
static int snmp_agent_config(oconfig_item_t *ci) {
  ....
  ret = snmp_agent_validate_data();
  if (ret != 0) {
    ERROR(PLUGIN_NAME ": Invalid configuration provided");
    snmp_agent_free_config();
    snmp_shutdown(PLUGIN_NAME);
    sfree(g_agent);
    return -EINVAL;
  }

  return 0;
} /* int snmp_agent_config */
```
