### ISSUE TITLE
impi segfault

### ISSUE THREAD

**Issue by faxm0dem** [collectd/collectd#2860]
*   Version of collectd: collectd-ci 5.8.0.74.g0c85475
*   Operating system / distribution: centos7
*   Vendor: Dell PowerEdge R740xd

## Expected behavior

shouldn't crash

## Actual behavior

collectd segfaults

### Config

```
TypesDB "/usr/share/collectd/types.db"

BaseDir "/var/lib/collectd"
CollectInternalStats "true"
FQDNLookup "true"
Interval "15"
PluginDir "/usr/lib64/collectd"
Timeout "2"
WriteQueueLimitHigh "20000"
WriteQueueLimitLow "20000"
LoadPlugin unixsock
<Plugin "unixsock">
DeleteSocket true
SocketFile "/var/tmp/collectd-sock"
SocketPerms "0770"
</Plugin>

LoadPlugin ipmi
<Plugin "ipmi">
  IgnoreSelected false
  Sensor "temperature-Inlet Temp system_board (7.1)"
  NotifySensorAdd false
  NotifySensorRemove false
  NotifySensorNotPresent false
  NotifyIPMIConnectionState false
  SELEnabled false
  SELClearEvent false
</Plugin>
```

# Run

```
$ collectd -C /var/tmp/collectd.conf -f
plugin_load: plugin "unixsock" successfully loaded.
plugin_load: plugin "ipmi" successfully loaded.
ipmi plugin: Legacy configuration found! Please update your config file.
unixsock plugin: Successfully deleted socket file "/var/tmp/collectd-sock".
plugin_dispatch_values: No write callback has been registered. Please load at least one output plugin, if you want the collected data to be stored.
Filter subsystem: Built-in target `write': Dispatching value to all write plugins failed with status 2 (ENOENT). Most likely this means you didn't load any write plugins.
Available write targets: [none]
Available write targets: [none]
Available write targets: [none]
Initialization complete, entering read-loop.
ipmi plugin: main(34.1).POST Pkg Repair states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).NVDIMM Info states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).NVDIMM Error states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).NVDIMM Warning states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).TPM Presence states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).OS Watchdog Time states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).LT/Flex Addr states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).QPI Link Err states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).Memory Config states.c(states_get_start): Error sending statesget command: 16
ipmi plugin: main(34.1).Chipset Info states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).CPU Link Info states.c(states_get_start): Error sending statesget command: 16
ipmi plugin: main(34.1).NonFatalPCIExpEr states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).FatalPCIExpEr states.c(states_get_start): Error sending statesget command: 16
ipmi plugin: main(34.1).NonFatalPCIErARI states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).FatalPCIErARI states.c(states_get_start): Error sending statesget command: 16
ipmi plugin: main(34.1).CPUMachineCheck states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).NonFatalSSDEr states.c(states_get_start): Error sending statesget command: 16
ipmi plugin: main(34.1).Fatal PCI SSD Er states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).NonFatalPCIErBus states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).FatalPCIErrOnBus states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).Chassis Mismatch states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).MRC Warning states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).MRC Warning states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).Link Error states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).Link Warning states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).Link Warning states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).QPIRC Warning states.c(states_get_start): Error sending statesget command: 16
ipmi plugin: main(34.1).QPIRC Warning states.c(states_get_start): Error sending statesget command: 16
ipmi plugin: main(34.1).CPU TDP states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).Additional Info states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).iDPT Mem Fail states.c(states_get_start): Error sending statesget command: 16
ipmi plugin: main(34.1).TXT Status states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).MSR Info Log states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).Fatal IO Error states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).Non Fatal PCI Er states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).Hdwr version err states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).POST Err states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).USB Over-current states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).Mem ECC Warning states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).Err Reg Pointer states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).Chipset Err states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).PCIE Fatal Err states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).Memory Mirrored states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).Memory Spared states.c(states_get_start): Error sending statesget command: 16
ipmi plugin: main(34.1).CPU Machine Chk states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).CPU Protocol Err states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).Unknown states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).SBE Log Disabled states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).PCI System Err states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).PCI Parity Err states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).ECC Uncorr Err states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(34.1).ECC Corr Err states.c(states_get_start): Error sending states get command: 16
ipmi plugin: main(3.2) entity.c(ipmi_entity_fetch_frus_cb): Unable to allocate the FRU: 26
ipmi plugin: main(3.1) entity.c(ipmi_entity_fetch_frus_cb): Unable to allocate the FRU: 26
ipmi plugin: main .1.20.11.0.0.0 fru.c(fru_inventory_area_handler): IPMI error gettingFRU inventory area: c9
ipmi plugin: main(11.5) entity.c(fru_fetched_ent_cb):Error fetching entity 11.5 FRU: 10000c9
ipmi plugin: main(5.20)(s,0) sdr.c(handle_sdr_data): SDR fetch error getting sdr 0x0: c1
ipmi plugin: main(0.20)(s,0) sdr.c(handle_sdr_data): SDR fetch error getting sdr 0x0: c1
ipmi plugin: main .1.20.10.0.3.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
ipmi plugin: main .1.20.2.0.0.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
ipmi plugin: main .1.20.2.0.0.0 normal_fru.c(fru_decode_multi_record_area): Data checksum for record 1 failed
ipmi plugin: main .1.20.2.0.0.0 fru.c(fetch_complete): Unable to decode FRU information
ipmi plugin: main(10.2) entity.c(fru_fetched_ent_cb):Error fetching entity 10.2 FRU: 26
ipmi plugin: main .1.20.1.0.0.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
ipmi plugin: main .1.20.1.0.0.0 normal_fru.c(fru_decode_multi_record_area): Data checksum for record 1 failed
ipmi plugin: main .1.20.1.0.0.0 fru.c(fetch_complete): Unable to decode FRU information
ipmi plugin: main(10.1) entity.c(fru_fetched_ent_cb):Error fetching entity 10.1 FRU: 26
ipmi plugin: main .1.20.4.0.3.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
Segmentation fault (core dumped)
```

# Trace

```
(gdb) bt full
#0  0x00007f9eadcb1d4b in __memcpy_ssse3_back () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f9eace960af in fru_decode_internal_use_area () from /lib64/libOpenIPMI.so.0
No symbol table info available.
#2  0x00007f9eace977f5 in process_fru_info () from /lib64/libOpenIPMI.so.0
No symbol table info available.
#3  0x00007f9eace79c89 in fru_call_decoder () from /lib64/libOpenIPMI.so.0
No symbol table info available.
#4  0x00007f9ead13237b in locked_list_iterate_prefunc_nolock ()
   from /lib64/libOpenIPMIutils.so.0
No symbol table info available.
#5  0x00007f9ead132454 in locked_list_iterate () from /lib64/libOpenIPMIutils.so.0
No symbol table info available.
#6  0x00007f9eace7b9ea in fetch_complete () from /lib64/libOpenIPMI.so.0
No symbol table info available.
#7  0x00007f9eace7bf05 in fru_data_handler () from /lib64/libOpenIPMI.so.0
No symbol table info available.
#8  0x00007f9eace63ae1 in deliver_rsp () from /lib64/libOpenIPMI.so.0
No symbol table info available.
#9  0x00007f9eace651ca in ll_rsp_handler () from /lib64/libOpenIPMI.so.0
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#10 0x00007f9eace63435 in ipmi_handle_rsp_item_copymsg () from /lib64/libOpenIPMI.so.0
No symbol table info available.
#11 0x00007f9eacec8085 in ipmi_dev_data_handler () from /lib64/libOpenIPMI.so.0
No symbol table info available.
#12 0x00007f9ead33aa7a in handle_selector_call () from /lib64/libOpenIPMIpthread.so.0
No symbol table info available.
#13 0x00007f9ead33cac6 in sel_select () from /lib64/libOpenIPMIpthread.so.0
No symbol table info available.
#14 0x00007f9ead33a304 in perform_one_op () from /lib64/libOpenIPMIpthread.so.0
No symbol table info available.
#15 0x00007f9ead54363d in c_ipmi_thread_main (user_data=0x557c46c7c4a0)
    at src/ipmi.c:974
        tv = {tv_sec = 1, tv_usec = 0}
        st = 0x557c46c7c4a0
#16 0x00007f9eae339e25 in start_thread () from /lib64/libpthread.so.0
#17 0x00007f9eadc5abad in clone () from /lib64/libc.so.6
```

**Comment by faxm0dem** [comment]
I tried this on different hardware. Some crashes, but not on all. However, I always see the error messages about FRU

**Comment by rpv-tomsk** [comment]
Which version of openIPMI was used?
You have to use at least OpenIPMI-2.0.22, IIRC.

**Comment by faxm0dem** [comment]
OpenIPMI-libs-2.0.23-2.el7.x86_64

**Comment by rpv-tomsk** [comment]
I think Collectd has nothing to do here...
You can refer to OpenIPMI project for help.
Also, you can try to update IPMI firmware....

Error messages for error codes in log output:

16 - EBUSY
26 - ETXTBSY

0xC1 - IPMI_INVALID_CMD_CC
0xC9 - IPMI_PARAMETER_OUT_OF_RANGE_CC

**Comment by rpv-tomsk** [comment]
Created an issue: https://sourceforge.net/p/openipmi/bugs/87/

**Comment by faxm0dem** [comment]
thanks @rpv-tomsk for your thorough analysis!
I'll see if updating the fw avoids the crash

**Comment by bingzhangdai** [comment]
Same issue here. May I know which package I should upgrade?

**Comment by faxm0dem** [comment]
It wasn't a package that we upgraded, but the server's baseboard management controller firmware.
