### ISSUE TITLE
ping crashes in ping_iterator_get_info

### ISSUE THREAD

**Issue by lilydjwg** [collectd/collectd#3079]
*   Version of collectd: 5.8.1
*   Operating system / distribution: Arch Linux
*   Kernel version (if applicable): 4.19.19

## Expected behavior

Don't crash.

## Actual behavior

Crashed with backtrace:

```
#0  0x00007fd94f3cb715 in __strlen_avx2 () from /usr/lib/libc.so.6
#1  0x00007fd94e4ee3fc in ping_iterator_get_info () from /usr/lib/liboping.so.0                                                        
#2  0x00007fd94f2565d9 in ping_dispatch_all (pingobj=0x7fd940000b40) at src/ping.c:156                                                 
#3  ping_thread (arg=<optimized out>) at src/ping.c:328
#4  0x00007fd94f443a9d in start_thread () from /usr/lib/libpthread.so.0                                                                
#5  0x00007fd94f367b23 in clone () from /usr/lib/libc.so.6
```

Both `iter->userhost` and `iter->hostname` are zeros as found by gdb.

## Steps to reproduce

I don't quite sure. In recent days it crashes in this manner a lot. There are a lot of `ping plugin: host SOME_HOST has not answered 10 PING requests, triggering resolve` but sometimes it crashes soon after starting without such errors.

There are also messages like `[37B blob data]`(I guess journald has hidden actual data) `ping plugin: Cannot find host .` `ping plugin: Cannot find host resolve.` sometimes.

I presume this happens only where the network is poor.

**Comment by github-k8n** [comment]
Also crashing here after it seems to try and resolve the hostname and fails.
(it is pinging a dynamic DNS hostname that might not be available and/or resolvable during the reconnect. it seems the ping plugin is just crashing instead of trying to resolve again later..)

Jul 04 04:38:30 [collectd] ping plugin: host XXXXX has not answered 5 PING requests, triggering resolve
Jul 04 04:38:35 [collectd] ping plugin: Cannot find host .
Jul 04 04:38:35 [kernel] [234455.649359] collectd[2136]: segfault at 41 ip 00007fc3c71da938 sp 00007fc3c5486960 error 4 in liboping.so.0.3.0[7fc3c71d8000+3000]

OS: Gentoo
Kernel: 5.13.0-gentoo
collectd version: 5.12.0 (app-metrics/collectd-5.12.0-r1)
