### ISSUE TITLE
Python plugin does not support "Unknown" values

### ISSUE THREAD

**Issue by centy** [collectd/collectd#339]
When trying to dispatch 'U' as a value exception is thrown. Collectd expects to have long as value.

**Comment by rubenk** [comment]
Indeed:

```
[2016-08-05 22:54:25]   File "/home/ruben/collectd-python/spam.py", line 7, in read
    vl.dispatch(values=['U'])
[2016-08-05 22:54:25] ValueError: could not convert string to float: U
[2016-08-05 22:54:25] read-function of plugin `python.spam' failed. Will suspend it for 120.000 seconds.
[2016-08-05 22:56:25] Unhandled python exception in read callback: ValueError: could not convert string to float: U
[2016-08-05 22:56:25] Traceback (most recent call last):
[2016-08-05 22:56:25]   File "/home/ruben/collectd-python/spam.py", line 7, in read
    vl.dispatch(values=['U'])
```

Not sure how much work it would be to add it. While we're at it, we should probably also add 'N'.

CC'ing @trenkel.

**Comment by octo** [comment]
math.nan, float('nan') and/or undef would all be good options for unknown values. I don't think "U" is.
–octo
Am 05.08.2016 23:17 schrieb Ruben Kerkhof <notifications@github.com>:Indeed:

[2016-08-05 22:54:25]   File "/home/ruben/collectd-python/spam.py", line 7, in read
    vl.dispatch(values=['U'])
[2016-08-05 22:54:25] ValueError: could not convert string to float: U
[2016-08-05 22:54:25] read-function of plugin `python.spam' failed. Will suspend it for 120.000 seconds.
[2016-08-05 22:56:25] Unhandled python exception in read callback: ValueError: could not convert string to float: U
[2016-08-05 22:56:25] Traceback (most recent call last):
[2016-08-05 22:56:25]   File "/home/ruben/collectd-python/spam.py", line 7, in read
    vl.dispatch(values=['U'])


Not sure how much work it would be to add it. While we're at it, we should probably also add 'N'.

CC'ing @trenkel.

**Comment by octo** [comment]
`math.nan`, `float('nan')` and/or `None` would all be good options for unknown values. I don't think `"U"` is.
–octo

**Comment by octo** [comment]
Judging from the code, the first two already work. I think this is working as intended.

**Comment by rubenk** [comment]
There's no nan attribute on the math module afaict, but `float('nan')` works:
```
$ ~/opt//sbin/collectd -f
option = ReadThreads; value = 1.000000;
option = WriteThreads; value = 1.000000;
Created new plugin context.
[2016-08-06 09:42:03] plugin_load: plugin "python" successfully loaded.
[2016-08-06 09:42:03] plugin_load: plugin "write_log" successfully loaded.
[2016-08-06 09:42:03] Initialization complete, entering read-loop.
[2016-08-06 09:42:03] write_log values:
rubenkerkhof_com.python_spam.gauge nan 1470469323
```

Thanks @octo!

**Comment by octo** [comment]
`math.nan` is new in Python 3.5: https://docs.python.org/3/library/math.html#math.nan

**Comment by rubenk** [comment]
Every day I learn something new... ;)
