### ISSUE TITLE
Deadlock in exec plugin after failed execvpe()

### ISSUE THREAD

**Issue by vladmovchan** [collectd/collectd#3440]
*   Version of collectd: 5.8.0
*   Operating system / distribution: Linux / Yocto-based
*   Kernel version (if applicable): Linux 4.1.38

## Expected behavior

When exec plugin fails to execute a script/application it reports a error and collectd child process terminates.

## Actual behavior

When `execvpe()`/`execvp()` of exec plugin fails, then child process could deadlock on attempt to grab the `file_lock` mutex in `logfile_print()`:
```
(gdb) bt
#0  0xb6fb20da in __syscall6 (f=0, e=0, d=0, c=240, b=128, a=-1225441080, n=240) at ./arch/arm/syscall_arch.h:98
#1  __syscall_cp_c (nr=240, u=-1225441080, v=128, w=240, x=0, y=0, z=0) at src/thread/pthread_cancel.c:31
#2  0xb6fb168c in __futex4_cp (to=<optimized out>, val=<optimized out>, op=<optimized out>, addr=<optimized out>) at src/thread/__timedwait.c:24
#3  __timedwait_cp (addr=addr@entry=0xb6f540c8 <file_lock+4>, val=val@entry=-2147483632, clk=clk@entry=0, at=at@entry=0x0, priv=priv@entry=128) at src/thread/__timedwait.c:52
#4  0xb6fb172a in __timedwait (addr=0xb6f540c8 <file_lock+4>, val=-2147483632, clk=clk@entry=0, at=at@entry=0x0, priv=priv@entry=128) at src/thread/__timedwait.c:68
#5  0xb6fb3724 in __pthread_mutex_timedlock (m=0xb6f540c4 <file_lock>, at=at@entry=0x0) at src/thread/pthread_mutex_timedlock.c:85
#6  0xb6fb364e in __pthread_mutex_lock (m=m@entry=0xb6f540c4 <file_lock>) at src/thread/pthread_mutex_lock.c:9
#7  0xb6f4287e in logfile_print (msg=0xb6df5898 "exec plugin: Failed to execute ``/usr/local/bin/run.sh'': No such file or directory", severity=<optimized out>, timestamp_time=<optimized out>)
    at src/logfile.c:115
#8  0x7f55d632 in plugin_log (level=level@entry=3, format=0xb6ef4fd0 "exec plugin: Failed to execute ``%s'': %s") at src/daemon/plugin.c:2248
#9  0xb6eef200 in exec_child (pl=0x7f5a7510, pl=0x7f5a7510, egid=-1226875651, gid=-1226875645, uid=<optimized out>, envp=0xb6df5cc0) at src/exec.c:306
#10 fork_child (pl=pl@entry=0x7f5a74d0, fd_in=fd_in@entry=0x0, fd_out=fd_out@entry=0xb6df736c, fd_err=fd_err@entry=0xb6df7370) at src/exec.c:494
#11 0xb6eef4d4 in exec_read_one (arg=0x7f5a74d0) at src/exec.c:551
#12 0xb6fb2cf6 in start (p=0xb6df7d68) at src/thread/pthread_create.c:192
(gdb) f 9
#9  0xb6eef200 in exec_child (pl=0x7f5a7510, pl=0x7f5a7510, egid=-1226875651, gid=-1226875645, uid=<optimized out>, envp=0xb6df5cc0) at src/exec.c:306
306       ERROR("exec plugin: Failed to execute ``%s'': %s", pl->exec,
(gdb) list
301     #else
302       environ = envp;
303       execvp(pl->exec, pl->argv);
304     #endif
305
306       ERROR("exec plugin: Failed to execute ``%s'': %s", pl->exec,
307             sstrerror(errno, errbuf, sizeof(errbuf)));
308       exit(-1);
309     } /* void exec_child }}} */
310
(gdb) f 7
#7  0xb6f4287e in logfile_print (msg=0xb6df5898 "exec plugin: Failed to execute ``/usr/local/bin/run.sh'': No such file or directory", severity=<optimized out>, timestamp_time=<optimized out>)
    at src/logfile.c:115
115       pthread_mutex_lock(&file_lock);
(gdb) list
110         strftime(timestamp_str, sizeof(timestamp_str), "%Y-%m-%d %H:%M:%S",
111                  &timestamp_tm);
112         timestamp_str[sizeof(timestamp_str) - 1] = '\0';
113       }
114
115       pthread_mutex_lock(&file_lock);
116
117       if (log_file == NULL) {
118         fh = stderr;
119       } else if (strcasecmp(log_file, "stderr") == 0)
(gdb)
```

## Steps to reproduce

*   Load exec plugin and add some non-existent executable there:
```
LoadPlugin "exec"
<Plugin exec>
    Exec "root" "/usr/local/bin/run.sh"
</Plugin>
```
*   Wait for some time. If exec plugin calls `fork()` when any of collectd process threads hold `file_lock` mutex the child process deadlocks.

**Comment by mrunge** [comment]
Thank you for reporting this issue and also the detailed analysis.
