### ISSUE TITLE
collectd coredumps with SIGSEGV when using NVMe devices on kernel that support Native NVMe multipathing.

### ISSUE THREAD

**Issue by MarkCRay** [collectd/collectd#4004]
*   Version of collectd: 5.9.2
*   Operating system / distribution: RHEL 8.4 with upstream kernel 
*   Kernel version (if applicable): 5.15.10  (upstream kernel)

## Expected behavior

(Description of the behavior / output that you expected)

Collectd doesn't coredump.

## Actual behavior

(Description of the behavior / output that you observed)

Collectd coredumps with SIGSEGV.    gdb shows the following stack trace:

(gdb) bt
#0  0x00007f19c891f42b in __strrchr_avx2 () from /lib64/libc.so.6
#1  0x00007f19c3f1dc40 in smart_handle_disk (serial=0x0, dev=0x0) at src/smart.c:190
#2  smart_read () at src/smart.c:235
#3  0x000000000040e634 in plugin_read_thread (args=<optimized out>) at src/daemon/plugin.c:526
#4  0x00007f19c8d9314a in start_thread () from /lib64/libpthread.so.0
#5  0x00007f19c88bedc3 in clone () from /lib64/libc.so.6

## Steps to reproduce

We have an nvme devices on the system.   There are 2 devices files for this - nvme0n1 and nvme0c0n1.   The nvme0c0n1 device doesn't have a serial number or device.   So both are NULL when passed to smart_handle_disk().   The smart_handle_disk() function handles the case when the serial number is NULL, but not the dev parameter.    

A simple check for a NULL dev parameter would fix this.  For example:

  if (use_serial && serial) {
    name = serial;
  } else if (dev) {
    name = strrchr(dev, '/');
    if (!name)
      return;
    name++;
  } else {
      return;
  }

The nvme0c0n1 device is related to the new Native NVMe multipath feature.   See also:  https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9-beta/html/managing_storage_devices/enabling-multipathing-on-nvme-devices_managing-storage-devices

**Comment by MarkCRay** [comment]
I didn't notice issue 3951 before.   Likely the same issue:
https://github.com/collectd/collectd/issues/3951
