### ISSUE TITLE
Frequent segfaults in libgcrypt

### ISSUE THREAD

**Issue by tvdavid** [collectd/collectd#851]
Hello,

I'm encountering very frequent segfaults in collectd 5.4.0-3ubuntu2 on Ubuntu 14.04 LTS. I'm aware that this isn't the latest upstream version, but the commits since then didn't seem relevant, so hopefully this'll be useful information.

Server config:
```
<Plugin "network">
        <Listen "0.0.0.0" "12345">
                SecurityLevel "Encrypt"
                AuthFile "/etc/collectd/auth_file"
        </Listen>
</Plugin>
```

Backtrace:
```
#0  0x00007f0042135bb9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 26395
        selftid = 26401
#1  0x00007f0042138fc8 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7fffd285d92c, sa_sigaction = 0x7fffd285d92c}, sa_mask = {
            __val = {139639086631004, 139639076441664, 193, 4294967295, 139639085269971, 0, 139638928955312, 0, 1112, 
              18446604434780596113, 0, 0, 0, 21474836480, 139639095558144, 139639086646128}}, sa_flags = 1099714118, 
          sa_restorer = 0x7f00418c4ea0 <__PRETTY_FUNCTION__.4370>}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007f004212ea76 in __assert_fail_base (fmt=0x7f0042280370 "/LC_MESSAGES/%N:", 
    assertion=assertion@entry=0x7f00418c4e46 "*lock == ((ath_mutex_t) 0)", file=file@entry=0x7f00418c4e40 "ath.c", 
    line=line@entry=193, function=function@entry=0x7f00418c4ea0 <__PRETTY_FUNCTION__.4370> "_gcry_ath_mutex_lock")
    at assert.c:92
        str = 0x7f0030009390 ""
        total = 4096
#3  0x00007f004212eb22 in __GI___assert_fail (assertion=assertion@entry=0x7f00418c4e46 "*lock == ((ath_mutex_t) 0)", 
    file=file@entry=0x7f00418c4e40 "ath.c", line=line@entry=193, 
    function=function@entry=0x7f00418c4ea0 <__PRETTY_FUNCTION__.4370> "_gcry_ath_mutex_lock") at assert.c:101
No locals.
#4  0x00007f004187eb6a in _gcry_ath_mutex_lock (lock=0x7f0041aecda0 <pool_lock>) at ath.c:193
        __PRETTY_FUNCTION__ = "_gcry_ath_mutex_lock"
#5  0x00007f00418b8b10 in lock_pool () at random-csprng.c:298
        err = <optimised out>
#6  0x00007f00418b9bde in _gcry_rngcsprng_fast_poll () at random-csprng.c:1266
No locals.
#7  0x00007f00418b8511 in _gcry_fast_random_poll () at random.c:259
No locals.
#8  0x00007f004188bfc2 in md_open (h=h@entry=0x7f0038c1d988, algo=algo@entry=8, secure=secure@entry=0, 
    hmac=hmac@entry=0) at md.c:503
        err = <optimised out>
        bufsize = <optimised out>
        ctx = 0x7f003000e988
        hd = 0x7f003000e570
        n = <optimised out>
#9  0x00007f004188caf0 in _gcry_md_hash_buffer (algo=algo@entry=8, digest=digest@entry=0x7f0038c1d9c0, 
    buffer=buffer@entry=0x7f0030006480, length=24) at md.c:1037
        h = 0x7f0041876dca <gcry_md_hash_buffer+26>
        err = <optimised out>
#10 0x00007f0041876e09 in gcry_md_hash_buffer (algo=algo@entry=8, digest=digest@entry=0x7f0038c1d9c0, 
    buffer=buffer@entry=0x7f0030006480, length=<optimised out>) at visibility.c:845
        __FUNCTION__ = "gcry_md_hash_buffer"
#11 0x00007f0041af1494 in network_get_aes256_cypher (se=se@entry=0x65d180, iv=iv@entry=0x7f0038c1dad0, 
    username=<optimised out>, iv_size=16) at network.c:536
        secret = 0x7f0030006480 "xxx"
        err = <optimised out>
        cyper_ptr = 0x65d1c8
        password_hash = "\t\000\000\000\000\000\000\000p\005\000\000\000\000\000\000\340\016\000(\000\177\000\000p\005\000\000\000\000\000"
#12 0x00007f0041af1b37 in parse_part_encr_aes256 (flags=0, ret_buffer_len=0x7f0038c1da80, ret_buffer=0x7f0038c1da88, 
    se=0x65d180) at network.c:1255
        buffer = 0x7f0028000ee0 "\002\020\005p"
        buffer_len = 1392
        err = <optimised out>
        part_size = 1392
        buffer_offset = 30
        payload_len = <optimised out>
        username_len = 8
        pea = {head = {type = 4098, length = 28677}, username_length = 0, username = 0x7f0030004500 "collectd", 
          iv = "\214l\323L\255\277f\242lP<\356E\330y>", 
          hash = ":\232n\232{\361\250x\301\025\n%a\r1\350\204\177\326", <incomplete sequence \351>}
        hash = ":\232n\232{\361\250x\301\025\n%a\r1\350\204\177\326", <incomplete sequence \351>
        cypher = <optimised out>
#13 parse_packet (se=0x65d180, buffer=0x7f0028000ee0, buffer_size=1392, flags=flags@entry=0, 
    username=username@entry=0x0) at network.c:1405
        pkg_length = <optimised out>
        pkg_type = <optimised out>
        status = <optimised out>
        vl = {values = 0x0, values_len = 0, time = 0, interval = 0, host = '\000' <repeats 63 times>, 
          plugin = '\000' <repeats 63 times>, plugin_instance = '\000' <repeats 63 times>, 
          type = '\000' <repeats 63 times>, type_instance = '\000' <repeats 63 times>, meta = 0x0}
        n = {severity = 0, time = 0, message = '\000' <repeats 255 times>, host = '\000' <repeats 63 times>, 
          plugin = '\000' <repeats 63 times>, plugin_instance = '\000' <repeats 63 times>, 
          type = '\000' <repeats 63 times>, type_instance = '\000' <repeats 63 times>, meta = 0x0}
        packet_was_signed = 0
        packet_was_encrypted = 0
        printed_ignore_warning = 0
#14 0x00007f0041af2949 in dispatch_thread (arg=<optimised out>) at network.c:2325
        ent = 0x7f0028000ec0
        se = <optimised out>
#15 0x00007f00426d7182 in start_thread (arg=0x7f0038c1e700) at pthread_create.c:312
        __res = <optimised out>
        pd = 0x7f0038c1e700
        now = <optimised out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139638928959232, -5205451564056487371, 0, 0, 139638928959936, 
                139638928959232, 5315079763539876405, 5314812413834648117}, mask_was_saved = 0}}, priv = {pad = {0x0, 
              0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimised out>
        pagesize_m1 = <optimised out>
        sp = <optimised out>
        freesize = <optimised out>
        __PRETTY_FUNCTION__ = "start_thread"
#16 0x00007f00421f9fbd in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#17 0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by rubenk** [comment]
Good to hear you've found the issue @tvdavid. I can't reproduce this on master so I'll assume that this is fixed, either in libgcrypt or one of our own commits.
